- name: set debian variables
  set_fact:
    tomcat: tomcat7
    tomcat_user: tomcat7 
    tomcat_conf: /etc/default/tomcat7 
    apache: apache2
    mysql_service: mysql
    cassandra_yaml: /etc/cassandra/cassandra.yaml
    cassandra_user: cassandra
    tomcat_webapps: /var/lib/tomcat7/webapps/
  when: ansible_os_family == "Debian"
  tags:
    - setfacts

- name: set redhat variables
  set_fact:
    tomcat: tomcat6
    tomcat_user: tomcat
    tomcat_conf: /etc/tomcat6/tomcat6.conf 
    apache: httpd
    mysql_service: mysqld
    cassandra_yaml: /etc/cassandra/conf/cassandra.yaml
    cassandra_user: cassandra
    tomcat_webapps: /var/lib/tomcat6/webapps/
  when: ansible_os_family == "RedHat"
  tags:
  - setfacts

#- name: set remote repositories (GBIF + CDN)
#  set_fact:
#     maven_repo: http://repository.gbif.org/content/groups/public/
#     data_file_repo: http://d1w4g4s73hkfzi.cloudfront.net/archives/20140610/

- name: set remote repositories (ALA)
  set_fact:
    maven_repo: http://maven.ala.org.au/repository
    name_indexes_repo: http://biocache.ala.org.au/archives/nameindexes/20140610/

- name: set shared virtualenv_home
  set_fact:
    virtualenv_home: /data
