neo4jUrl: http://neo4j.com/artifact.php?name=neo4j-community-1.9.8-unix.tar.gz
neo4jVersion: 1.9.8
neo4jDirName: "neo4j-community-{{neo4jVersion}}"
neo4jTarFile: "{{neo4jDirName}}.tar.gz"
neo4jXDir: /data
neo4jApplicationDir: neo4j-community-Application
