VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.6.3"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.hostname = "opentree.ala.dev"
  config.vm.network :private_network, ip: "10.1.1.2"
  config.vm.network "forwarded_port", guest: 7474, host: 7474
  config.vm.network "forwarded_port", guest: 7476, host: 7476
  config.vm.network "forwarded_port", guest: 7478, host: 7478
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  
  # these machines require some memory to operate the apps
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
  end

  # totally insecure, but this is local dev: make the vagrant default the root key
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.vm.provision "shell", inline: "sudo cp -r /home/vagrant/.ssh /root/.ssh"
end
